/* SPRING MVC PROJECT 
    ITEM : MULTIPLEX RESERVATION SYTEM
    NEEDS______
    1. 상영관 개수의 동적 처리
    2. 각 상영관 좌석 수의 동적처리
    3. 좌석의 동적 배치
    4. WEB을 이용한 예약처리
    5. WEB을 이용한 영화관 관리
    6. 좌석별 요금의 동적처리
    7. 연령별 요금의 동적처리
*/
/* MULTIPLEX TABLESPACE CREATION :: SYS */
-- CREATION
CREATE TABLESPACE MULTIPLEX
DATAFILE 'D:\Spring\database\TS\MULTIPLEX_01.ORA'
SIZE 10M AUTOEXTEND ON NEXT 5M MAXSIZE 100M;

/* TEAM DBA CREATION : SYS */
-- CREATION
CREATE USER ADMINISTRATOR IDENTIFIED BY "5678"
DEFAULT TABLESPACE MULTIPLEX
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON MULTIPLEX;

ALTER USER ADMINISTRATOR IDENTIFIED BY "5678";
-- PRIVILEAGE
GRANT DBA TO ADMINISTRATOR;

  -- CHECK
  SELECT USERNAME AS "USER", 
         ACCOUNT_STATUS AS "STATUS",  
         DEFAULT_TABLESPACE AS "TABLESPACE",
         GRANTED_ROLE AS "ROLE"
  FROM DBA_USERS DU INNER JOIN DBA_ROLE_PRIVS RP ON DU.USERNAME = RP.GRANTEE
  WHERE USERNAME = 'ADMINISTRATOR';

  -- CHECK
  SELECT TABLESPACE_NAME, STATUS, CONTENTS FROM DBA_TABLESPACES WHERE TABLESPACE_NAME = 'MULTIPLEX';
  SELECT FILE_NAME, TABLESPACE_NAME, BYTES, STATUS FROM DBA_DATA_FILES WHERE TABLESPACE_NAME = 'MULTIPLEX';
  SELECT BYTES, BLOCKS FROM DBA_FREE_SPACE WHERE TABLESPACE_NAME = 'MULTIPLEX';

  -- TABLESPACE 조회 :: DBA가 생성
  CREATE OR REPLACE VIEW TSINFO
  AS
  SELECT TS.TABLESPACE_NAME AS "TABLESPACE",
         TS.STATUS AS "TS_STATUS",
         TS.CONTENTS AS "TYPE",
         DF.FILE_NAME AS "FILE_NAME",
         DF.BYTES /(1024*1024) || 'M' AS "SIZE",
         DF.STATUS AS "DF_STATUS",
         FS.BYTES /(1024*1024) || 'M' AS "AVAILABLE"         
  FROM DBA_TABLESPACES TS INNER JOIN DBA_DATA_FILES DF ON TS.TABLESPACE_NAME = DF.TABLESPACE_NAME
                          INNER JOIN DBA_FREE_SPACE FS ON TS.TABLESPACE_NAME = FS.TABLESPACE_NAME;
  SELECT * FROM TSINFO              
  WHERE TS.TABLESPACE_NAME = 'MULTIPLEX';

/* TEAM DEV CREATION : TEAM DBA */
-- CREATION
CREATE USER DEVELOPER IDENTIFIED BY "5678"
DEFAULT TABLESPACE MULTIPLEX
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON MULTIPLEX;
-- GRANT
GRANT CONNECT, RESOURCE TO DEVELOPER;
