/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-01-04 01:04:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Sign Up Page</title>\r\n");
      out.write("    <meta name=\"description\" content=\"Sign Up Page\">\r\n");
      out.write("    <meta name=\"author\" content=\"Sookyeong\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"image/icia-logo.png\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <header id=\"header\">\r\n");
      out.write("        <h1><a href=\"https://www.icia.co.kr/\"><img src=\"image/icia-logo.png\" alt=\"\"></a></h1>\r\n");
      out.write("    </header>\r\n");
      out.write("    <div id=\"message\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("    <!-- Secion -->\r\n");
      out.write("    <section id=\"section\">\r\n");
      out.write("        <form action=\"Join\" method=\"post\">\r\n");
      out.write("            <div class=\"id\">\r\n");
      out.write("                <h3 class=\"join__title\"><label for=\"id\">아이디</label></h3>\r\n");
      out.write("                <span class=\"input__space\"><input type=\"text\" name=\"joinInfo\" minlength=\"3\" maxlength=\"10\" title=\"ID\" required></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"pw\">\r\n");
      out.write("                <h3 class=\"join__title\"><label for=\"password\">비밀번호</label></h3>\r\n");
      out.write("                <span class=\"input__space\"><input type=\"password\" name=\"joinInfo\" minlength=\"4\" maxlength=\"10\" title=\"비밀번호 입력\" required></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"pw2\">\r\n");
      out.write("                <h3 class=\"join__title\"><label for=\"password\">비밀번호 재확인</label></h3>\r\n");
      out.write("                <span class=\"input__space\"><input type=\"password\" id=\"password\" minlength=\"4\" maxlength=\"10\" title=\"비밀번호 재확인 입력\" required onBlur=\"pwdCheck()\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"name\">\r\n");
      out.write("                <h3 class=\"join__title\"><label for=\"name\">이름</label></h3>\r\n");
      out.write("                <span class=\"input__space\"><input type=\"text\" name=\"joinInfo\" title=\"이름\" required></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- \r\n");
      out.write("            <div class=\"birthday\">\r\n");
      out.write("                <h3 class=\"join__title\"><label for=\"birthday\">생년월일</label></h3>\r\n");
      out.write("                <div class=\"bir__wrap\">\r\n");
      out.write("                    <div class=\"bir__wrap__item\">\r\n");
      out.write("                        <span class=\"input__space\"><input type=\"text\" id=\"birthday\" maxlength=\"4\" placeholder=\"년(4자)\"></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"bir__wrap__item\">                   \r\n");
      out.write("                        <select name=\"birthday\" id=\"birthday\">\r\n");
      out.write("                                <option value=\"Month\">월</option>\r\n");
      out.write("                                <option value=\"January\">1</option>\r\n");
      out.write("                                <option value=\"Febuary\">2</option>\r\n");
      out.write("                                <option value=\"March\">3</option>\r\n");
      out.write("                                <option value=\"April\">4</option>\r\n");
      out.write("                                <option value=\"May\">5</option>\r\n");
      out.write("                                <option value=\"June\">6</option>\r\n");
      out.write("                                <option value=\"July\">7</option>\r\n");
      out.write("                                <option value=\"Agust\">8</option>\r\n");
      out.write("                                <option value=\"September\">9</option>\r\n");
      out.write("                                <option value=\"October\">10</option>\r\n");
      out.write("                                <option value=\"November\">11</option>\r\n");
      out.write("                                <option value=\"December\">12</option>\r\n");
      out.write("                        </select>                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"bir__wrap__item\">\r\n");
      out.write("                        <span class=\"input__space\"><input type=\"text\" id=\"birthday\" maxlength=\"2\" placeholder=\"일\"></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"gender\">\r\n");
      out.write("                <h3 class=\"join__title\"><label for=\"gender\">성별</label></h3>\r\n");
      out.write("                <div class=\"radio__gender\">\r\n");
      out.write("                    <span class=\"radio__gender__item\"><input type=\"radio\" name=\"gender\" id=\"gender\" value=\"Male\">남자</span>\r\n");
      out.write("                    <span class=\"radio__gender__item\"><input type=\"radio\" name=\"gender\" id=\"gender\" value=\"Female\">여자</span>\r\n");
      out.write("                    <span class=\"radio__gender__item\"><input type=\"radio\" name=\"gender\" id=\"gender\" value=\"\r\n");
      out.write("                        Not selected\">선택 안함</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"email\">\r\n");
      out.write("                <h3 class=\"join__title\"><label for=\"email\">본인 확인 이메일</label><small style=\"color:#bdbdbd;\">(선택)</small></h3>\r\n");
      out.write("                <span class=\"input__space\"><input type=\"email\" id=\"email\" placeholder=\"선택입력\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("             -->\r\n");
      out.write("            <div class=\"tel\">\r\n");
      out.write("                <h3 class=\"join__title\"><label for=\"tel\">휴대전화</label></h3>\r\n");
      out.write("                <div class=\"tel__wrap\">\r\n");
      out.write("                \t<!-- \r\n");
      out.write("                    <div class=\"tel__wrap__select\">                       \r\n");
      out.write("                        <select name=\"tel\" id=\"tel\">\r\n");
      out.write("                            <option value=\"233\">가나 +233</option>\r\n");
      out.write("                            <option value=\"674\">나우루 +674</option>\r\n");
      out.write("                            <option value=\"82\" selected>대한민국 +82</option>\r\n");
      out.write("                            <option value=\"856\">라오스 +856</option>\r\n");
      out.write("                            <option value=\"52\">멕시코 +52</option>\r\n");
      out.write("                            <option value=\"32\">벨기에 +32</option>\r\n");
      out.write("                            <option value=\"65\">싱가포르 +65</option>\r\n");
      out.write("                            <option value=\"353\">아일랜드 +353</option>\r\n");
      out.write("                        </select>                       \r\n");
      out.write("                    </div>\r\n");
      out.write("                     -->\r\n");
      out.write("                    <div class=\"tel__wrap__input\">\r\n");
      out.write("                        <span class=\"input__space\"><input type=\"tel\" name=\"joinInfo\" placeholder=\"전화번호 입력\"></span>\r\n");
      out.write("                        <!-- \r\n");
      out.write("                        <span class=\"button\"><button>인증번호 받기</button></span>\r\n");
      out.write("                         -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- \r\n");
      out.write("                    <div class=\"tel__wrap__input2\">\r\n");
      out.write("                        <input type=\"tel\" id=\"tel\" placeholder=\"인증번호 입력하세요\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                     -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"submit\">\r\n");
      out.write("                <button type=\"submit\" id=\"submit\">가입하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        <span onClick=\"movePage(true)\">[LogIn]</span>\r\n");
      out.write("        <span onClick=\"movePage(false)\">[Previous]</span>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <footer id=\"footer\">\r\n");
      out.write("        <span class=\"footer__icon\"><a href=\"https://www.icia.co.kr/\"><img src=\"image/icia-logo.png\" alt=\"\" id=\"footer__icon\"></a></span>\r\n");
      out.write("        <span class=\"footer__rights\">Copyright <b>ICIA.</b> All Rights Reserved.</span>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("function movePage(selection){\r\n");
      out.write("\tvar form = document.createElement(\"form\");\r\n");
      out.write("\t\r\n");
      out.write("\tform.action = (selection)?\"LogInForm\":\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prev}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\tform.method = \"post\";\r\n");
      out.write("\t\r\n");
      out.write("\t// Current Page정보\r\n");
      out.write("\tvar page = document.createElement(\"input\");\r\n");
      out.write("\tpage.type = \"hidden\";\r\n");
      out.write("\tpage.name = \"page\";\r\n");
      out.write("\tpage.value = \"JoinForm\";\r\n");
      out.write("\tform.appendChild(page);\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.body.appendChild(form);\r\n");
      out.write("\tform.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function pwdCheck(){\r\n");
      out.write("\t// 패스워드와 패스워드재확인의 데이터가 일치하는지 확인\r\n");
      out.write("\tvar pwd = document.getElementsByName(\"joinInfo\")[1];\r\n");
      out.write("\tvar pwdCopy = document.getElementById(\"password\");\r\n");
      out.write("\t\r\n");
      out.write("\tif(pwd.value != pwdCopy.value){\r\n");
      out.write("\t\tpwd.value = \"\";\r\n");
      out.write("\t\tpwdCopy.value = \"\";\r\n");
      out.write("\t\tpwd.placeholder = \"패스워드가 일치하지 않아요~ 다시 입력 부탁드려요\"\r\n");
      out.write("\t\tpwd.focus();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
